# Generated by Django 4.1.1 on 2024-05-13 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0037_auto_20240425_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_item',
            name='party',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.party'),
        ),
    ]
